### ISSUE TITLE
关于如何实现1Dswin核心思想的请教

### ISSUE THREAD

**Issue by STU-ECHO** [chgwan/SwinTransformer_1d#1]
我看代码了，但是我太菜了看不明白，如果您有时间的话，请问能否文字叙述一下在swin基础上的1Dswin的实现的主要点。当然没时间也没有关系，请不要有压力，期待您的回复

**Comment by chgwan** [comment]
你好，其实主要是利用Swin Shifting windows 的思想放在 1D 的数据处理上
